// =============================================================================
// KDBA V2 — 20 Curated Industry Template Definitions
// =============================================================================

import { TemplateDefinition } from '@/types';

export const TEMPLATES_DEFINITIONS: TemplateDefinition[] = [
  // 1. MODERN RESTAURANT
  {
    id: 'tpl_restaurant',
    name: 'Aura Fine Dining & Lounge',
    slug: 'modern-restaurant',
    industry: 'RESTAURANT',
    style: 'Warm Dark Luxury • Photography Focused',
    description: 'Bespoke gastronomy experience with featured dishes, chef highlights, and direct reservation flow.',
    previewImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_restaurant',
      name: 'Aura Fine Dining',
      slug: 'aura-dining',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#120f0d',
        secondaryColor: '#211a16',
        accentColor: '#d4af37',
        backgroundColor: '#0c0a09',
        surfaceColor: '#1c1917',
        textColor: '#fdfbf7',
        mutedTextColor: '#a8a29e',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
        buttonStyle: 'solid',
      },
      business: {
        name: 'Aura Fine Dining',
        tagline: 'Artisan Gastronomy & Curated Cellar',
        description: 'Immerse your senses in seasonal tasting menus crafted with locally harvested ingredients and rare vintages.',
        phone: '+1 (555) 849-2001',
        email: 'reservations@auradining.com',
        address: '450 North Canon Drive, Beverly Hills, CA 90210',
        businessHours: [
          { days: 'Tuesday – Thursday', hours: '5:30 PM – 10:30 PM' },
          { days: 'Friday – Saturday', hours: '5:00 PM – 11:30 PM' },
          { days: 'Sunday', hours: '5:00 PM – 9:30 PM' },
        ],
      },
      pages: [
        {
          id: 'page_res_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_res_nav',
              type: 'navbar',
              variant: 'centered',
              enabled: true,
              props: {
                brandName: 'AURA',
                links: [
                  { label: 'Menu', url: '#menu' },
                  { label: 'Story', url: '#about' },
                  { label: 'Atmosphere', url: '#gallery' },
                  { label: 'Hours', url: '#hours' },
                ],
                ctaText: 'Reserve Table',
                ctaUrl: '#contact',
              },
            },
            {
              id: 'sec_res_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Michelin Recognized 2026',
                headline: 'An Unforgettable Culinary Symphony',
                subheadline: 'Experience avant-garde tasting menus paired with world-class cellar selections in an intimate setting.',
                primaryCtaText: 'Reserve a Table',
                primaryCtaUrl: '#contact',
                secondaryCtaText: 'Explore Dinner Menu',
                secondaryCtaUrl: '#menu',
                imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_res_about',
              type: 'about',
              variant: 'story',
              enabled: true,
              props: {
                badge: 'Our Philosophy',
                headline: 'Rooted in Seasonality & Fire',
                description: 'Executive Chef Julian Rostova choreographs each evening around wood-fire culinary craft, heirloom produce, and artisanal fermentation.',
                imageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=1000&auto=format&fit=crop&q=80',
                features: ['Wood-Fired Mastery', 'Rare Estate Vintages', 'Private Chef Tables'],
              },
            },
            {
              id: 'sec_res_menu',
              type: 'products',
              variant: 'menu-list',
              enabled: true,
              props: {
                badge: 'Seasonal Tasting',
                headline: 'Signature Dinner Selections',
                subheadline: 'Seven-course tasting experience curated weekly based on market arrivals.',
                items: [
                  { name: 'Wagyu A5 Carpaccio', price: '$48.00', description: 'Truffle emulsion, smoked sea salt, toasted brioche tuile.' },
                  { name: 'Pan-Seared Hokkaido Scallops', price: '$52.00', description: 'Sunchoke purée, brown butter dashi, oscietra caviar.' },
                  { name: 'Oak-Smoked Duck Breast', price: '$64.00', description: 'Caramelized shallot tarte tatin, sour cherry reduction.' },
                  { name: 'Valrhona Dark Chocolate Ganache', price: '$26.00', description: 'Smoked hazelnut praline, gold leaf, vanilla bean gelato.' },
                ],
              },
            },
            {
              id: 'sec_res_gallery',
              type: 'gallery',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Visual Experience',
                headline: 'Atmosphere & Cellar Highlights',
                images: [
                  'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=600&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop&q=80',
                ],
              },
            },
            {
              id: 'sec_res_hours',
              type: 'opening-hours',
              variant: 'card-table',
              enabled: true,
              props: {
                badge: 'Dining Schedule',
                headline: 'Operating Hours & Reservations',
                note: 'Tasting menus require 2.5 hours. Valet parking available on North Canon Dr.',
                schedule: [
                  { days: 'Tuesday – Thursday', hours: '5:30 PM – 10:30 PM' },
                  { days: 'Friday & Saturday', hours: '5:00 PM – 11:30 PM' },
                  { days: 'Sunday', hours: '5:00 PM – 9:30 PM' },
                  { days: 'Monday', hours: 'Closed for Private Events' },
                ],
              },
            },
            {
              id: 'sec_res_contact',
              type: 'contact',
              variant: 'split-form',
              enabled: true,
              props: {
                badge: 'Reservations',
                headline: 'Reserve Your Experience',
                subheadline: 'For parties of six or more or private dining buyouts, please submit details below.',
                buttonText: 'Request Reservation',
                email: 'reservations@auradining.com',
                phone: '+1 (555) 849-2001',
                address: '450 North Canon Drive, Beverly Hills, CA',
              },
            },
            {
              id: 'sec_res_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: {
                brandName: 'AURA',
                tagline: 'Refined culinary craft and exceptional hospitality in Beverly Hills.',
                copyright: '© 2026 Aura Hospitality Group. All rights reserved.',
              },
            },
          ],
        },
      ],
    },
  },

  // 2. ARTISAN CAFE
  {
    id: 'tpl_cafe',
    name: 'Komorebi Specialty Coffee',
    slug: 'artisan-cafe',
    industry: 'CAFE',
    style: 'Warm Editorial • Japanese Minimalism',
    description: 'Single-origin pour-overs, handcrafted matcha, and artisanal Japanese pastries.',
    previewImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_cafe',
      name: 'Komorebi Coffee',
      slug: 'komorebi-coffee',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#171412',
        secondaryColor: '#2b241e',
        accentColor: '#c28854',
        backgroundColor: '#110f0d',
        surfaceColor: '#231d18',
        textColor: '#f9f6f0',
        mutedTextColor: '#b8aba0',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '8px',
        buttonStyle: 'solid',
      },
      business: {
        name: 'Komorebi Coffee',
        tagline: 'Single Origin Roasters & Tea House',
        phone: '+1 (555) 293-8471',
        email: 'hello@komorebicoffee.com',
        address: '1820 4th Street, Berkeley, CA 94710',
      },
      pages: [
        {
          id: 'page_cafe_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_cafe_nav',
              type: 'navbar',
              variant: 'floating',
              enabled: true,
              props: {
                brandName: 'KOMOREBI',
                ctaText: 'Visit Cafe',
                ctaUrl: '#hours',
              },
            },
            {
              id: 'sec_cafe_hero',
              type: 'hero',
              variant: 'editorial',
              enabled: true,
              props: {
                badge: 'Direct Trade Micro-Lots',
                headline: 'Crafted with Silence, Patience & Pure Craft',
                subheadline: 'Ethically sourced single-origin beans roasted lightly to celebrate origin terroir, floral notes, and natural sweetness.',
                primaryCtaText: 'View Coffee Menu',
                primaryCtaUrl: '#menu',
                secondaryCtaText: 'Our Roastery Story',
                secondaryCtaUrl: '#about',
                imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_cafe_products',
              type: 'products',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Daily Roast',
                headline: 'Featured Micro-Lots & Brews',
                subheadline: 'Hand-poured slow bar extractions and seasonal lattes.',
                items: [
                  { name: 'Geisha Panama Boquete', price: '$12.00', description: 'Jasmine blossom, bergamot, peach nectar, delicate tea-like body.', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80' },
                  { name: 'Ceremonial Uji Matcha Latte', price: '$8.50', description: 'First harvest stone-ground green tea whisked with oat milk.', imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80' },
                  { name: 'Ethiopia Yirgacheffe Natural', price: '$9.00', description: 'Blueberry jam, lavender honey, vibrant Meyer lemon acidity.', imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80' },
                ],
              },
            },
            {
              id: 'sec_cafe_hours',
              type: 'opening-hours',
              variant: 'card-table',
              enabled: true,
              props: {
                badge: 'Open Daily',
                headline: 'Brewing Hours',
                schedule: [
                  { days: 'Monday – Friday', hours: '7:00 AM – 5:00 PM' },
                  { days: 'Saturday & Sunday', hours: '8:00 AM – 6:00 PM' },
                ],
              },
            },
            {
              id: 'sec_cafe_footer',
              type: 'footer',
              variant: 'minimal-centered',
              enabled: true,
              props: {
                brandName: 'Komorebi Coffee',
                tagline: 'Quiet moments with exceptional coffee.',
              },
            },
          ],
        },
      ],
    },
  },

  // 3. DENTAL CLINIC
  {
    id: 'tpl_dental',
    name: 'Apex Modern Dentistry',
    slug: 'dental-clinic',
    industry: 'DENTAL',
    style: 'Clean • Trustworthy • High-Tech Medical',
    description: 'Comprehensive restorative, implant, and aesthetic dentistry in a serene clinic environment.',
    previewImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_dental',
      name: 'Apex Dentistry',
      slug: 'apex-dentistry',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0b192c',
        secondaryColor: '#1e3e62',
        accentColor: '#00adb5',
        backgroundColor: '#070f1e',
        surfaceColor: '#132845',
        textColor: '#ffffff',
        mutedTextColor: '#94a3b8',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '16px',
        buttonStyle: 'solid',
      },
      business: {
        name: 'Apex Dental Care',
        phone: '+1 (555) 720-4100',
        email: 'appointments@apexdental.com',
        address: '820 Westlake Avenue, Suite 300, Seattle, WA',
      },
      pages: [
        {
          id: 'page_den_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_den_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: {
                brandName: 'Apex Dental',
                ctaText: 'Book Appointment',
                ctaUrl: '#contact',
              },
            },
            {
              id: 'sec_den_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'State-of-the-Art Dental Studio',
                headline: 'Transforming Smiles with Precision & Comfort',
                subheadline: 'Experience anxiety-free dentistry with 3D digital imaging, gentle laser care, and world-class cosmetic specialists.',
                primaryCtaText: 'Schedule Consultation',
                primaryCtaUrl: '#contact',
                secondaryCtaText: 'Our Treatments',
                secondaryCtaUrl: '#services',
                imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_den_services',
              type: 'services',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Treatments',
                headline: 'Comprehensive Dental Solutions',
                items: [
                  { title: 'Invisalign & Alignment', description: 'Clear custom aligners designed for rapid, discreet teeth straightening.', icon: 'Zap' },
                  { title: 'Porcelain Veneers', description: 'Handcrafted ultra-thin porcelain for a luminous, natural smile.', icon: 'Sparkles' },
                  { title: 'Dental Implants', description: 'Permanent titanium restorations restoring 100% natural bite function.', icon: 'ShieldCheck' },
                ],
              },
            },
            {
              id: 'sec_den_stats',
              type: 'stats',
              variant: 'counter-grid',
              enabled: true,
              props: {
                headline: 'Patient Trust & Excellence',
                items: [
                  { value: '15,000+', label: 'Patients Treated' },
                  { value: '99.4%', label: 'Satisfaction Score' },
                  { value: '22+', label: 'Years Serving Community' },
                  { value: '0%', label: 'Interest Financing Available' },
                ],
              },
            },
            {
              id: 'sec_den_faq',
              type: 'faq',
              variant: 'accordion',
              enabled: true,
              props: {
                badge: 'Patient Questions',
                headline: 'Frequently Asked Questions',
                items: [
                  { question: 'Do you accept major dental insurance plans?', answer: 'Yes, we work with all PPO insurance providers and maximize your in-network benefits.' },
                  { question: 'Is the initial consultation painful?', answer: 'Not at all. We utilize gentle 3D digital scanning with zero radiation discomfort.' },
                ],
              },
            },
            {
              id: 'sec_den_contact',
              type: 'contact',
              variant: 'split-form',
              enabled: true,
              props: {
                badge: 'Book Today',
                headline: 'Schedule Your Visit',
                buttonText: 'Confirm Booking Request',
              },
            },
            {
              id: 'sec_den_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: {
                brandName: 'Apex Dental Care',
                tagline: 'Gentle, modern, and compassionate dentistry.',
              },
            },
          ],
        },
      ],
    },
  },

  // 4. PRIVATE HEALTHCARE CLINIC
  {
    id: 'tpl_healthcare',
    name: 'Vanguard Medical Institute',
    slug: 'healthcare-clinic',
    industry: 'HEALTHCARE',
    style: 'Sapphire Medical • Clinical Precision',
    description: 'Executive physicals, longevity diagnostics, and specialist medical care.',
    previewImage: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_health',
      name: 'Vanguard Medical',
      slug: 'vanguard-medical',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0a1828',
        secondaryColor: '#178582',
        accentColor: '#00adb5',
        backgroundColor: '#060e18',
        surfaceColor: '#12253b',
        textColor: '#f8fafc',
        mutedTextColor: '#94a3b8',
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
      },
      business: {
        name: 'Vanguard Medical Institute',
        phone: '+1 (555) 300-8800',
        email: 'intake@vanguardhealth.com',
        address: '100 Medical Center Parkway, Boston, MA',
      },
      pages: [
        {
          id: 'page_health_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_h_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'Vanguard Medical', ctaText: 'Patient Portal', ctaUrl: '#contact' },
            },
            {
              id: 'sec_h_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Integrative Medicine & Longevity',
                headline: 'World-Class Diagnostics & Preventive Medicine',
                subheadline: 'Board-certified physicians providing personalized health optimization and concierge medical care.',
                primaryCtaText: 'Schedule Consultation',
                primaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_h_team',
              type: 'team',
              variant: 'grid-cards',
              enabled: true,
              props: {
                badge: 'Physicians',
                headline: 'Senior Clinical Faculty',
                items: [
                  { name: 'Dr. Evelyn Sterling, MD', role: 'Chief of Cardiology', bio: 'Harvard Medical School faculty with 20+ years in preventive diagnostics.', avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80' },
                  { name: 'Dr. Michael Chen, MD', role: 'Longevity Specialist', bio: 'Pioneer in metabolic optimization and biometric health profiling.', avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80' },
                ],
              },
            },
            {
              id: 'sec_h_cta',
              type: 'cta',
              variant: 'centered-card',
              enabled: true,
              props: {
                headline: 'Take Control of Your Longevity',
                subheadline: 'Book an comprehensive biomarker assessment today.',
                primaryCtaText: 'Request Patient Intake',
                primaryCtaUrl: '#contact',
              },
            },
            {
              id: 'sec_h_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Vanguard Medical Institute' },
            },
          ],
        },
      ],
    },
  },

  // 5. PREMIUM SALON
  {
    id: 'tpl_salon',
    name: 'Maison Luxe Hair & Beauty',
    slug: 'premium-salon',
    industry: 'SALON',
    style: 'Chic Rose-Gold • Fashion Editorial',
    description: 'Celebrity hair styling, balayage master colorists, and couture treatments.',
    previewImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_salon',
      name: 'Maison Luxe Salon',
      slug: 'maison-luxe',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#191516',
        secondaryColor: '#2b2124',
        accentColor: '#e0a96d',
        backgroundColor: '#110d0e',
        surfaceColor: '#20181b',
        textColor: '#ffffff',
        mutedTextColor: '#c4b5b8',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '20px',
      },
      business: {
        name: 'Maison Luxe Studio',
        phone: '+1 (555) 920-1122',
        email: 'appointments@maisonluxesalon.com',
        address: '320 Rodeo Drive, Suite 100, Beverly Hills, CA',
      },
      pages: [
        {
          id: 'page_salon_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_s_nav',
              type: 'navbar',
              variant: 'floating',
              enabled: true,
              props: { brandName: 'MAISON LUXE', ctaText: 'Book Stylist', ctaUrl: '#contact' },
            },
            {
              id: 'sec_s_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Master Colorists & Stylists',
                headline: 'Couture Hair Architecture & Luminous Color',
                subheadline: 'Transformative hair experiences crafted by top editorial colorists in an ultra-luxurious sanctuary.',
                primaryCtaText: 'Reserve Appointment',
                primaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_s_services',
              type: 'services',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Services',
                headline: 'Artisan Hair & Scalp Treatments',
                items: [
                  { title: 'Signature French Balayage', description: 'Hand-painted dimensional brightness tailored to facial bone structure.', icon: 'Sparkles' },
                  { title: 'Keratin Caviar Silk Infusion', description: 'Deep restorative moisture bonding for mirror-glass shine.', icon: 'Heart' },
                  { title: 'Editorial Haircut & Blowout', description: 'Precision dry cutting followed by luxury botanical blowouts.', icon: 'Scissors' },
                ],
              },
            },
            {
              id: 'sec_s_gallery',
              type: 'gallery',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Lookbook',
                headline: 'Client Transformations',
                images: [
                  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=600&auto=format&fit=crop&q=80',
                ],
              },
            },
            {
              id: 'sec_s_contact',
              type: 'contact',
              variant: 'split-form',
              enabled: true,
              props: {
                badge: 'Reservations',
                headline: 'Book Your Session',
                buttonText: 'Book with Stylist',
              },
            },
            {
              id: 'sec_s_footer',
              type: 'footer',
              variant: 'minimal-centered',
              enabled: true,
              props: { brandName: 'Maison Luxe Studio' },
            },
          ],
        },
      ],
    },
  },

  // 6. WELLNESS SPA
  {
    id: 'tpl_spa',
    name: 'Aethel Sanctuary & Spa',
    slug: 'wellness-spa',
    industry: 'SPA',
    style: 'Calm Sage & Warm Neutral • Natural Luxury',
    description: 'Hydrotherapy thermal baths, botanical massage therapy, and sound healing rituals.',
    previewImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_spa',
      name: 'Aethel Sanctuary',
      slug: 'aethel-spa',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#141c17',
        secondaryColor: '#222e26',
        accentColor: '#84a98c',
        backgroundColor: '#0d1310',
        surfaceColor: '#1b251f',
        textColor: '#f0f5f1',
        mutedTextColor: '#a3b899',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '16px',
      },
      business: {
        name: 'Aethel Spa & Wellness',
        phone: '+1 (555) 739-1002',
        email: 'serenity@aethelspa.com',
        address: '500 Mountain View Trail, Aspen, CO',
      },
      pages: [
        {
          id: 'page_spa_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_spa_nav',
              type: 'navbar',
              variant: 'centered',
              enabled: true,
              props: { brandName: 'AETHEL', ctaText: 'Book Ritual', ctaUrl: '#contact' },
            },
            {
              id: 'sec_spa_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Holistic Mountain Retreat',
                headline: 'Awaken Body, Mind & Spirit in Stillness',
                subheadline: 'Immerse in mineral hot springs, herbal cedar saunas, and organic botanical massage therapies.',
                primaryCtaText: 'Explore Rituals',
                primaryCtaUrl: '#services',
                imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_spa_services',
              type: 'services',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Healing Rituals',
                headline: 'Curated Spa Journeys',
                items: [
                  { title: 'Hot Stone Basalt Therapy', description: 'Warm river stones soothe chronic muscle fatigue and enhance micro-circulation.', icon: 'Heart' },
                  { title: 'Wild Alpine Herbal Wrap', description: 'Detoxifying mountain clay and lavender infusions to replenish skin vitality.', icon: 'Sparkles' },
                  { title: 'Sound Bath & Breathwork', description: 'Tibetan crystal singing bowl frequencies facilitating deep restorative theta states.', icon: 'Activity' },
                ],
              },
            },
            {
              id: 'sec_spa_contact',
              type: 'contact',
              variant: 'split-form',
              enabled: true,
              props: {
                badge: 'Reservations',
                headline: 'Reserve Your Sanctuary Journey',
                buttonText: 'Request Booking',
              },
            },
            {
              id: 'sec_spa_footer',
              type: 'footer',
              variant: 'minimal-centered',
              enabled: true,
              props: { brandName: 'Aethel Sanctuary' },
            },
          ],
        },
      ],
    },
  },

  // 7. FITNESS STUDIO
  {
    id: 'tpl_fitness',
    name: 'Iron & Pulse Athletic Club',
    slug: 'fitness-studio',
    industry: 'FITNESS',
    style: 'High-Energy Crimson & Obsidian • Bold Typography',
    description: 'Elite personal coaching, HIIT performance training, and biometric body transformation.',
    previewImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_fitness',
      name: 'Iron & Pulse Club',
      slug: 'iron-pulse',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0f0f11',
        secondaryColor: '#1d1c21',
        accentColor: '#e63946',
        backgroundColor: '#09090b',
        surfaceColor: '#18181b',
        textColor: '#ffffff',
        mutedTextColor: '#a1a1aa',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '8px',
      },
      business: {
        name: 'Iron & Pulse Fitness',
        phone: '+1 (555) 482-9011',
        email: 'train@ironpulseclub.com',
        address: '1400 Broadway, New York, NY',
      },
      pages: [
        {
          id: 'page_fit_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_f_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'IRON & PULSE', ctaText: 'Join Club', ctaUrl: '#pricing' },
            },
            {
              id: 'sec_f_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Elite Performance Training',
                headline: 'Unleash Your Absolute Human Potential',
                subheadline: 'World-class strength conditioning, functional hypertrophy, and athletic coaching built for peak athletes.',
                primaryCtaText: 'Start 7-Day Trial',
                primaryCtaUrl: '#pricing',
                secondaryCtaText: 'View Class Schedule',
                secondaryCtaUrl: '#services',
                imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_f_pricing',
              type: 'pricing',
              variant: 'tier-cards',
              enabled: true,
              props: {
                badge: 'Memberships',
                headline: 'Choose Your Athletic Tier',
                items: [
                  { name: 'Core Athlete', price: '$149', period: '/mo', description: 'Full access to weight room and open conditioning floor.', features: ['Open gym floor', 'Locker & towel service', '1 Monthly coaching audit'] },
                  { name: 'Black Tier Elite', price: '$279', period: '/mo', description: 'Unlimited performance classes, recovery cold plunge, and sauna.', isPopular: true, features: ['Unlimited HIIT classes', 'Cold plunge & sauna access', 'Biometric body scans', '2 Personal training sessions'] },
                ],
              },
            },
            {
              id: 'sec_f_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Iron & Pulse Athletic Club' },
            },
          ],
        },
      ],
    },
  },

  // 8. REAL ESTATE CONSULTANT
  {
    id: 'tpl_real_estate',
    name: 'Vanguard Luxury Realty',
    slug: 'real-estate-consultant',
    industry: 'REAL_ESTATE',
    style: 'Navy & Champagne Gold • Luxury Architecture',
    description: 'Premier residential real estate advisory, coastal estates, and ultra-high-net-worth acquisitions.',
    previewImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_re',
      name: 'Vanguard Realty',
      slug: 'vanguard-realty',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0a192f',
        secondaryColor: '#172a45',
        accentColor: '#c5a880',
        backgroundColor: '#060f1e',
        surfaceColor: '#112240',
        textColor: '#ffffff',
        mutedTextColor: '#8892b0',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
      },
      business: {
        name: 'Vanguard Luxury Properties',
        phone: '+1 (555) 777-9000',
        email: 'estates@vanguardluxury.com',
        address: '400 Ocean Avenue, Santa Monica, CA',
      },
      pages: [
        {
          id: 'page_re_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_re_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'VANGUARD ESTATES', ctaText: 'Schedule Private Showing', ctaUrl: '#contact' },
            },
            {
              id: 'sec_re_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Exclusive Coastal Estates',
                headline: 'Enduring Architecture & Unmatched Horizons',
                subheadline: 'Representing extraordinary architectural homes and private island sanctuaries across California & Florida.',
                primaryCtaText: 'View Featured Portfolio',
                primaryCtaUrl: '#portfolio',
                imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_re_portfolio',
              type: 'portfolio',
              variant: 'grid-hover',
              enabled: true,
              props: {
                badge: 'Current Listings',
                headline: 'Notable Architectural Residences',
                items: [
                  { title: 'The Bel Air Promontory', category: '$28,500,000 • Bel Air, CA', year: '7 Bed • 11 Bath', imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80' },
                  { title: 'Malibu Carbon Beach Modern', category: '$19,200,000 • Malibu, CA', year: '5 Bed • 6 Bath', imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80' },
                  { title: 'Tribeca Penthouse Residence', category: '$14,800,000 • New York, NY', year: '4 Bed • 5 Bath', imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80' },
                ],
              },
            },
            {
              id: 'sec_re_contact',
              type: 'contact',
              variant: 'split-form',
              enabled: true,
              props: {
                badge: 'Private Consultation',
                headline: 'Acquisition & Listing Inquiries',
                buttonText: 'Submit Inquiry',
              },
            },
            {
              id: 'sec_re_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: { brandName: 'Vanguard Luxury Properties' },
            },
          ],
        },
      ],
    },
  },

  // 9. ARCHITECTURE STUDIO
  {
    id: 'tpl_architecture',
    name: 'Forma & Space Architects',
    slug: 'architecture-studio',
    industry: 'ARCHITECTURE',
    style: 'Minimalist Monochrome • Photography Heavy',
    description: 'Award-winning contemporary architectural design, structural engineering, and urban pavilions.',
    previewImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_arch',
      name: 'Forma Architects',
      slug: 'forma-architects',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#121212',
        secondaryColor: '#1e1e1e',
        accentColor: '#ffffff',
        backgroundColor: '#0a0a0a',
        surfaceColor: '#171717',
        textColor: '#f5f5f5',
        mutedTextColor: '#a3a3a3',
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '0px',
      },
      business: {
        name: 'Forma & Space Architecture',
        phone: '+1 (555) 492-3301',
        email: 'studio@forma-architects.com',
        address: '900 Broadway, 11th Floor, New York, NY',
      },
      pages: [
        {
          id: 'page_arch_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_a_nav',
              type: 'navbar',
              variant: 'split',
              enabled: true,
              props: { brandName: 'FORMA / ARCH', ctaText: 'Initiate Project', ctaUrl: '#contact' },
            },
            {
              id: 'sec_a_hero',
              type: 'hero',
              variant: 'editorial',
              enabled: true,
              props: {
                badge: 'AIA National Honor Award 2025',
                headline: 'Sculpting Space, Materiality & Light',
                subheadline: 'We design timeless residential, civic, and cultural structures grounded in environmental harmony.',
                primaryCtaText: 'Selected Works',
                primaryCtaUrl: '#portfolio',
                imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_a_portfolio',
              type: 'portfolio',
              variant: 'grid-hover',
              enabled: true,
              props: {
                badge: 'Works',
                headline: 'Landmark Built Projects',
                items: [
                  { title: 'The Glass Pavilion at Big Sur', category: 'Residential • 2025', imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80' },
                  { title: 'Kyoto Cultural Center', category: 'Civic • 2024', imageUrl: 'https://images.unsplash.com/photo-1493397212122-2b85dda8106b?w=800&auto=format&fit=crop&q=80' },
                ],
              },
            },
            {
              id: 'sec_a_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Forma & Space Architects' },
            },
          ],
        },
      ],
    },
  },

  // 10. LUXURY INTERIOR DESIGN
  {
    id: 'tpl_interior',
    name: 'Atelier Maison Interiors',
    slug: 'luxury-interior-design',
    industry: 'INTERIOR_DESIGN',
    style: 'Luxury Cream & Bronze • Elegant Serif',
    description: 'High-end residential interior architecture, bespoke furniture procurement, and turnkey design.',
    previewImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_interior',
      name: 'Atelier Maison',
      slug: 'atelier-maison',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#1c1815',
        secondaryColor: '#2b2420',
        accentColor: '#d6a354',
        backgroundColor: '#120f0d',
        surfaceColor: '#241e1a',
        textColor: '#faf7f2',
        mutedTextColor: '#bfae9e',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
      },
      business: {
        name: 'Atelier Maison Interiors',
        phone: '+1 (555) 901-4422',
        email: 'design@ateliermaison.com',
        address: '520 West 24th Street, Chelsea, NY',
      },
      pages: [
        {
          id: 'page_int_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_i_nav',
              type: 'navbar',
              variant: 'centered',
              enabled: true,
              props: { brandName: 'ATELIER MAISON', ctaText: 'Consultation', ctaUrl: '#contact' },
            },
            {
              id: 'sec_i_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Bespoke Residential Spaces',
                headline: 'Curated Environments of Enduring Elegance',
                subheadline: 'Crafting bespoke interior narratives blending rare textiles, custom millwork, and museum-grade art collections.',
                primaryCtaText: 'Explore Portfolios',
                primaryCtaUrl: '#portfolio',
                imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_i_footer',
              type: 'footer',
              variant: 'minimal-centered',
              enabled: true,
              props: { brandName: 'Atelier Maison Interiors' },
            },
          ],
        },
      ],
    },
  },

  // 11. PROFESSIONAL PHOTOGRAPHER
  {
    id: 'tpl_photographer',
    name: 'Kaelen Vance Visuals',
    slug: 'professional-photographer',
    industry: 'PHOTOGRAPHER',
    style: 'Deep Obsidian • Edge-to-Edge Portfolio',
    description: 'Commercial advertising, fashion editorial, and fine art landscape photography.',
    previewImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_photo',
      name: 'Kaelen Vance Photography',
      slug: 'kaelen-vance',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0a0a0a',
        secondaryColor: '#141414',
        accentColor: '#ffffff',
        backgroundColor: '#050505',
        surfaceColor: '#121212',
        textColor: '#f5f5f5',
        mutedTextColor: '#737373',
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '0px',
      },
      business: {
        name: 'Kaelen Vance Visuals',
        email: 'agent@kaelenvance.com',
        phone: '+1 (555) 830-1920',
      },
      pages: [
        {
          id: 'page_photo_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_p_nav',
              type: 'navbar',
              variant: 'minimal',
              enabled: true,
              props: { brandName: 'KAELEN VANCE', ctaText: 'Inquire Booking', ctaUrl: '#contact' },
            },
            {
              id: 'sec_p_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Commercial & Editorial',
                headline: 'Capturing Raw Emotion & Timeless Light',
                subheadline: 'Available worldwide for commercial campaigns, fashion editorials, and luxury architectural assignments.',
                primaryCtaText: 'View Archive',
                primaryCtaUrl: '#gallery',
                imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_p_gallery',
              type: 'gallery',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Selected Archive',
                headline: 'Recent Commissions',
                images: [
                  'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
                  'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80',
                ],
              },
            },
            {
              id: 'sec_p_footer',
              type: 'footer',
              variant: 'minimal-centered',
              enabled: true,
              props: { brandName: 'Kaelen Vance Visuals' },
            },
          ],
        },
      ],
    },
  },

  // 12. DIGITAL CREATIVE AGENCY
  {
    id: 'tpl_agency',
    name: 'Nexus Interactive Studio',
    slug: 'digital-creative-agency',
    industry: 'CREATIVE_AGENCY',
    style: 'Electric Indigo & Neon Violet • Bento Grids',
    description: 'Next-generation branding, full-stack product engineering, and high-impact digital campaigns.',
    previewImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_agency',
      name: 'Nexus Studio',
      slug: 'nexus-studio',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#090d16',
        secondaryColor: '#131b2e',
        accentColor: '#6366f1',
        backgroundColor: '#05080f',
        surfaceColor: '#0f172a',
        textColor: '#f8fafc',
        mutedTextColor: '#94a3b8',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '16px',
      },
      business: {
        name: 'Nexus Interactive Agency',
        phone: '+1 (555) 600-4000',
        email: 'growth@nexusstudio.io',
        address: '500 Howard Street, San Francisco, CA',
      },
      pages: [
        {
          id: 'page_ag_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_ag_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'NEXUS', ctaText: 'Start Project', ctaUrl: '#contact' },
            },
            {
              id: 'sec_ag_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Creative Technology Studio',
                headline: 'We Build Digital Products that Dominate Markets',
                subheadline: 'Partnering with visionary founders and enterprise leaders to architect category-defining digital brands.',
                primaryCtaText: 'View Case Studies',
                primaryCtaUrl: '#portfolio',
                secondaryCtaText: 'Explore Capabilities',
                secondaryCtaUrl: '#services',
                imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_ag_features',
              type: 'features',
              variant: 'bento-grid',
              enabled: true,
              props: {
                badge: 'Capabilities',
                headline: 'Precision Craft Across Every Medium',
              },
            },
            {
              id: 'sec_ag_process',
              type: 'process',
              variant: 'steps-timeline',
              enabled: true,
              props: {
                badge: 'Methodology',
                headline: 'From Zero to Hyper-Scale',
              },
            },
            {
              id: 'sec_ag_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: { brandName: 'Nexus Interactive Agency' },
            },
          ],
        },
      ],
    },
  },

  // 13. SAAS / SOFTWARE COMPANY
  {
    id: 'tpl_software',
    name: 'HyperScale Cloud Platform',
    slug: 'saas-software-company',
    industry: 'SOFTWARE_SAAS',
    style: 'Modern Tech Gradient • Product UI Previews',
    description: 'Cloud infrastructure monitoring, automated deployment workflows, and real-time observability.',
    previewImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_saas',
      name: 'HyperScale',
      slug: 'hyperscale-cloud',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0b0f19',
        secondaryColor: '#172033',
        accentColor: '#38bdf8',
        backgroundColor: '#070a12',
        surfaceColor: '#101726',
        textColor: '#f1f5f9',
        mutedTextColor: '#94a3b8',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
      },
      business: {
        name: 'HyperScale Cloud Inc.',
        email: 'sales@hyperscale.io',
        address: '100 Montgomery St, Suite 1200, San Francisco, CA',
      },
      pages: [
        {
          id: 'page_saas_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_saas_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'HyperScale', ctaText: 'Start Free Trial', ctaUrl: '#pricing' },
            },
            {
              id: 'sec_saas_hero',
              type: 'hero',
              variant: 'centered',
              enabled: true,
              props: {
                badge: 'Next-Gen Cloud Orchestration',
                headline: 'Automate Infrastructure at Lightning Speed',
                subheadline: 'Eliminate downtime and accelerate release velocity with our AI-driven cloud monitoring suite.',
                primaryCtaText: 'Get Started Free',
                primaryCtaUrl: '#pricing',
                secondaryCtaText: 'Request Demo',
                secondaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_saas_features',
              type: 'features',
              variant: 'bento-grid',
              enabled: true,
              props: {
                badge: 'Features',
                headline: 'Everything Engineering Teams Need',
              },
            },
            {
              id: 'sec_saas_pricing',
              type: 'pricing',
              variant: 'tier-cards',
              enabled: true,
              props: {
                badge: 'Pricing',
                headline: 'Predictable Pricing for High-Growth Teams',
                items: [
                  { name: 'Developer', price: '$49', period: '/mo', description: 'Up to 5 nodes and standard telemetry logs.', features: ['5 Active Nodes', '7-Day Log Retention', 'Community Discord Support'] },
                  { name: 'Scale Team', price: '$199', period: '/mo', isPopular: true, description: 'Unlimited clusters, real-time alerts, and anomaly detection.', features: ['Unlimited Clusters', '30-Day Log Retention', '24/7 SLA Guarantee', 'Custom Webhooks'] },
                  { name: 'Enterprise', price: 'Custom', period: '', description: 'Dedicated VPC peering, SOC2 compliance, and custom SLAs.', features: ['Dedicated Support Pod', 'Custom VPC Tunneling', '99.999% Uptime SLA'] },
                ],
              },
            },
            {
              id: 'sec_saas_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: { brandName: 'HyperScale Cloud Inc.' },
            },
          ],
        },
      ],
    },
  },

  // 14. BUSINESS CONSULTANT
  {
    id: 'tpl_consultant',
    name: 'Apex Strategic Advisory',
    slug: 'business-consultant',
    industry: 'CONSULTING',
    style: 'Corporate Slate & Emerald • High ROI Proof',
    description: 'Management consulting, M&A restructuring, and operational excellence for Fortune 500 executives.',
    previewImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_consult',
      name: 'Apex Advisory',
      slug: 'apex-advisory',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0b1622',
        secondaryColor: '#16283d',
        accentColor: '#10b981',
        backgroundColor: '#070e17',
        surfaceColor: '#122030',
        textColor: '#ffffff',
        mutedTextColor: '#94a3b8',
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
      },
      business: {
        name: 'Apex Strategic Advisory',
        phone: '+1 (555) 720-3000',
        email: 'partners@apexstrategic.com',
        address: '200 Park Avenue, 40th Floor, New York, NY',
      },
      pages: [
        {
          id: 'page_cons_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_c_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'APEX STRATEGY', ctaText: 'Schedule Briefing', ctaUrl: '#contact' },
            },
            {
              id: 'sec_c_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Executive Advisory & Growth',
                headline: 'Driving Transformational Enterprise Value',
                subheadline: 'We guide boards and CEOs through complex restructurings, M&A capital deployment, and digital modernization.',
                primaryCtaText: 'Schedule Consultation',
                primaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_c_stats',
              type: 'stats',
              variant: 'counter-grid',
              enabled: true,
              props: {
                headline: 'Delivering Measured Financial Impact',
                items: [
                  { value: '$4.2B+', label: 'Transaction Value Advised' },
                  { value: '38%', label: 'Average Margin Improvement' },
                  { value: '180+', label: 'Enterprise Engagements' },
                  { value: '98%', label: 'Client Retention Rate' },
                ],
              },
            },
            {
              id: 'sec_c_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Apex Strategic Advisory' },
            },
          ],
        },
      ],
    },
  },

  // 15. LAW FIRM
  {
    id: 'tpl_law',
    name: 'Sterling & Vance LLP',
    slug: 'law-firm',
    industry: 'LAW_FIRM',
    style: 'Deep Navy & Warm Parchment • Restrained Authority',
    description: 'Corporate litigation, securities regulation, and high-stakes dispute resolution.',
    previewImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_law',
      name: 'Sterling & Vance LLP',
      slug: 'sterling-vance-law',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0c1524',
        secondaryColor: '#17243b',
        accentColor: '#c5a059',
        backgroundColor: '#070d17',
        surfaceColor: '#121c2e',
        textColor: '#ffffff',
        mutedTextColor: '#94a3b8',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '8px',
      },
      business: {
        name: 'Sterling & Vance LLP',
        phone: '+1 (555) 940-2020',
        email: 'intake@sterlingvance.com',
        address: '100 Federal Street, 35th Floor, Boston, MA',
      },
      pages: [
        {
          id: 'page_law_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_l_nav',
              type: 'navbar',
              variant: 'centered',
              enabled: true,
              props: { brandName: 'STERLING & VANCE', ctaText: 'Confidential Inquiry', ctaUrl: '#contact' },
            },
            {
              id: 'sec_l_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Chambers Global Band 1 Ranked',
                headline: 'Uncompromising Legal Counsel in High-Stakes Matters',
                subheadline: 'Protecting your enterprise with decades of courtroom trial mastery, regulatory insight, and strategic precision.',
                primaryCtaText: 'Our Practice Areas',
                primaryCtaUrl: '#services',
                secondaryCtaText: 'Consult a Partner',
                secondaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_l_services',
              type: 'services',
              variant: 'grid',
              enabled: true,
              props: {
                badge: 'Practice Areas',
                headline: 'Specialized Legal Domains',
                items: [
                  { title: 'Corporate Governance & M&A', description: 'Cross-border joint ventures, hostile defense, and shareholder disputes.', icon: 'Briefcase' },
                  { title: 'Securities & Regulatory Defense', description: 'SEC investigations, antitrust compliance, and internal fraud audits.', icon: 'ShieldCheck' },
                  { title: 'Commercial Appellate Trial', description: 'Federal and international arbitration before supreme jurisdictions.', icon: 'Compass' },
                ],
              },
            },
            {
              id: 'sec_l_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: { brandName: 'Sterling & Vance LLP' },
            },
          ],
        },
      ],
    },
  },

  // 16. COACHING / EDUCATION INSTITUTE
  {
    id: 'tpl_coaching',
    name: 'Ascend Executive Academy',
    slug: 'coaching-education-institute',
    industry: 'EDUCATION',
    style: 'Engaging Amber & Violet • Student Transformations',
    description: 'Executive leadership masterclasses, tech career accelerators, and certificate programs.',
    previewImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_coach',
      name: 'Ascend Academy',
      slug: 'ascend-academy',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#120d24',
        secondaryColor: '#231a42',
        accentColor: '#f59e0b',
        backgroundColor: '#0c0818',
        surfaceColor: '#1c1536',
        textColor: '#ffffff',
        mutedTextColor: '#b4a9cc',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '16px',
      },
      business: {
        name: 'Ascend Executive Academy',
        phone: '+1 (555) 430-8100',
        email: 'admissions@ascendacademy.com',
      },
      pages: [
        {
          id: 'page_coach_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_coach_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'ASCEND ACADEMY', ctaText: 'Apply Now', ctaUrl: '#contact' },
            },
            {
              id: 'sec_coach_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Admissions Open for Q3 Cohort',
                headline: 'Accelerate Your Path to the C-Suite',
                subheadline: 'Intensive 12-week executive mastery curriculum taught by former Fortune 100 CEOs and Silicon Valley founders.',
                primaryCtaText: 'Explore Cohorts',
                primaryCtaUrl: '#services',
                imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_coach_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Ascend Executive Academy' },
            },
          ],
        },
      ],
    },
  },

  // 17. MODERN SCHOOL
  {
    id: 'tpl_school',
    name: 'Horizon International Preparatory',
    slug: 'modern-school',
    industry: 'SCHOOL',
    style: 'Friendly Sapphire & Sunshine Gold • Academic Heritage',
    description: 'K-12 preparatory academy blending STEAM curriculum, global languages, and character leadership.',
    previewImage: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_school',
      name: 'Horizon Prep',
      slug: 'horizon-prep',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0a1d37',
        secondaryColor: '#133560',
        accentColor: '#3b82f6',
        backgroundColor: '#071426',
        surfaceColor: '#0f294d',
        textColor: '#ffffff',
        mutedTextColor: '#94a3b8',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '12px',
      },
      business: {
        name: 'Horizon International School',
        phone: '+1 (555) 234-9900',
        email: 'admissions@horizonprep.edu',
        address: '500 Campus Green Way, Austin, TX',
      },
      pages: [
        {
          id: 'page_sch_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_sch_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'HORIZON PREP', ctaText: 'Schedule Campus Tour', ctaUrl: '#contact' },
            },
            {
              id: 'sec_sch_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Excellence in K-12 STEAM',
                headline: 'Inspiring Tomorrow’s Global Innovators & Leaders',
                subheadline: 'Empowering young minds through world-class science labs, international baccalaureate studies, and creative arts.',
                primaryCtaText: 'Admissions Process',
                primaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_sch_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: { brandName: 'Horizon International Preparatory' },
            },
          ],
        },
      ],
    },
  },

  // 18. BOUTIQUE HOTEL
  {
    id: 'tpl_hotel',
    name: 'The Grand Miramar Boutique Resort',
    slug: 'boutique-hotel',
    industry: 'HOTEL',
    style: 'Warm Luxury Bronze & Slate • Bespoke Suites',
    description: 'Oceanfront suites, rooftop cocktail lounge, infinity pool, and concierge yacht charter.',
    previewImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_hotel',
      name: 'Grand Miramar Resort',
      slug: 'grand-miramar',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#12151c',
        secondaryColor: '#1f2430',
        accentColor: '#d4af37',
        backgroundColor: '#0c0e14',
        surfaceColor: '#181c26',
        textColor: '#fdfbf7',
        mutedTextColor: '#9ca3af',
        headingFont: 'Playfair Display, Georgia, serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '16px',
      },
      business: {
        name: 'The Grand Miramar Hotel',
        phone: '+1 (555) 780-5500',
        email: 'concierge@grandmiramar.com',
        address: '1200 Coastal Highway, Santa Barbara, CA',
      },
      pages: [
        {
          id: 'page_hot_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_hot_nav',
              type: 'navbar',
              variant: 'centered',
              enabled: true,
              props: { brandName: 'THE GRAND MIRAMAR', ctaText: 'Check Availability', ctaUrl: '#contact' },
            },
            {
              id: 'sec_hot_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Pacific Coast Sanctuary',
                headline: 'Where Coastal Serenity Meets Unrivaled Luxury',
                subheadline: 'Private cliffside villas with infinity plunge pools, ocean-to-table dining, and dedicated butler service.',
                primaryCtaText: 'Reserve Your Suite',
                primaryCtaUrl: '#contact',
                imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_hot_footer',
              type: 'footer',
              variant: 'multi-column',
              enabled: true,
              props: { brandName: 'The Grand Miramar Boutique Resort' },
            },
          ],
        },
      ],
    },
  },

  // 19. TRAVEL AGENCY
  {
    id: 'tpl_travel',
    name: 'Wanderlust Expeditions',
    slug: 'travel-agency',
    industry: 'TRAVEL',
    style: 'Vibrant Azure & Coral • Bucket List Adventures',
    description: 'Curated luxury safaris, Antarctic expeditions, and private jet cultural journeys.',
    previewImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    featured: false,
    document: {
      id: 'doc_travel',
      name: 'Wanderlust Expeditions',
      slug: 'wanderlust-travel',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0a192f',
        secondaryColor: '#142c4c',
        accentColor: '#f97316',
        backgroundColor: '#061020',
        surfaceColor: '#0f223d',
        textColor: '#ffffff',
        mutedTextColor: '#94a3b8',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '16px',
      },
      business: {
        name: 'Wanderlust Luxury Travel',
        phone: '+1 (555) 919-4400',
        email: 'voyages@wanderlusttravel.com',
      },
      pages: [
        {
          id: 'page_trv_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_trv_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'WANDERLUST', ctaText: 'Plan Your Journey', ctaUrl: '#contact' },
            },
            {
              id: 'sec_trv_hero',
              type: 'hero',
              variant: 'fullscreen',
              enabled: true,
              props: {
                badge: 'Curated Expeditions Worldwide',
                headline: 'Extraordinary Journeys to the Ends of the Earth',
                subheadline: 'Bespoke itineraries, luxury private guides, and exclusive access to the world’s most breathtaking destinations.',
                primaryCtaText: 'Explore Destinations',
                primaryCtaUrl: '#portfolio',
                imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1600&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_trv_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Wanderlust Luxury Travel' },
            },
          ],
        },
      ],
    },
  },

  // 20. AUTOMOTIVE / CAR DETAILING
  {
    id: 'tpl_automotive',
    name: 'Apex Precision Detailing & Wrap Studio',
    slug: 'automotive-car-detailing',
    industry: 'AUTOMOTIVE',
    style: 'High-Contrast Obsidian & Hyper Red • Ceramic Gloss',
    description: 'Ceramic Pro 9H coating, XPEL paint protection film, and bespoke vehicle customization.',
    previewImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80',
    featured: true,
    document: {
      id: 'doc_auto',
      name: 'Apex Precision Detailing',
      slug: 'apex-detailing',
      status: 'PUBLISHED',
      theme: {
        primaryColor: '#0a0a0c',
        secondaryColor: '#17171c',
        accentColor: '#ef4444',
        backgroundColor: '#060608',
        surfaceColor: '#121217',
        textColor: '#ffffff',
        mutedTextColor: '#a1a1aa',
        headingFont: 'Plus Jakarta Sans, sans-serif',
        bodyFont: 'Inter, sans-serif',
        borderRadius: '10px',
      },
      business: {
        name: 'Apex Detailing Studio',
        phone: '+1 (555) 830-4900',
        email: 'quotes@apexdetailstudio.com',
        address: '780 Industrial Parkway, Miami, FL',
      },
      pages: [
        {
          id: 'page_auto_home',
          title: 'Home',
          slug: '/',
          sections: [
            {
              id: 'sec_auto_nav',
              type: 'navbar',
              variant: 'standard',
              enabled: true,
              props: { brandName: 'APEX DETAILING', ctaText: 'Get Quote', ctaUrl: '#contact' },
            },
            {
              id: 'sec_auto_hero',
              type: 'hero',
              variant: 'split-image',
              enabled: true,
              props: {
                badge: 'Certified XPEL & Ceramic Pro Studio',
                headline: 'Flawless Paint Protection & Supercar Craft',
                subheadline: 'Protect your investment with multi-stage paint correction, self-healing PPF, and ceramic gloss coatings.',
                primaryCtaText: 'Request Custom Quote',
                primaryCtaUrl: '#contact',
                secondaryCtaText: 'View Detailing Packages',
                secondaryCtaUrl: '#pricing',
                imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80',
              },
            },
            {
              id: 'sec_auto_pricing',
              type: 'pricing',
              variant: 'tier-cards',
              enabled: true,
              props: {
                badge: 'Protection Packages',
                headline: 'Precision Detailing Tiers',
                items: [
                  { name: 'Gold Ceramic Coating', price: '$1,299', period: '', description: '5-Year Ceramic Pro 9H with single-stage machine paint polish.', features: ['Paint decontamination', 'Single-stage polish', '5-Year warranty coating', 'Hydrophobic windshield'] },
                  { name: 'Track Armor PPF', price: '$2,899', period: '', isPopular: true, description: 'Full front clip XPEL Ultimate Plus self-healing film.', features: ['Bumper, hood, fenders, mirrors', 'Self-healing technology', '10-Year manufacturer warranty', 'Ceramic topcoat included'] },
                ],
              },
            },
            {
              id: 'sec_auto_footer',
              type: 'footer',
              variant: 'compact',
              enabled: true,
              props: { brandName: 'Apex Precision Detailing' },
            },
          ],
        },
      ],
    },
  },
];

/**
 * Returns a template definition by id or slug.
 */
export function getTemplateByIdOrSlug(idOrSlug: string): TemplateDefinition | undefined {
  return TEMPLATES_DEFINITIONS.find((t) => t.id === idOrSlug || t.slug === idOrSlug);
}
